<script type="text/javascript" src="http://www.recordstree.com:8081/public/js/jquery/jquery_v1_10.js"></script>
<script type="text/javascript" src="http://www.recordstree.com:8081/public/js/jquery/jquery.once.js"></script>
<script type="text/javascript" src="http://www.recordstree.com:8081/public/js/plugins/jquery.flexslider-min.js"></script>
<script type="text/javascript" src="http://www.recordstree.com:8081/public/js/plugins/jquery.jcarousel.min.js"></script>
<script type="text/javascript" src="http://www.recordstree.com:8081/public/js/jquery.easing-1.3.min.js"></script>
<script type="text/javascript" src="http://www.recordstree.com:8081/public/js/plugins/jquery.tipsy.js"></script>
<script type="text/javascript" src="http://www.recordstree.com:8081/public/js/plugins/jquery.prettyPhoto.js"></script>
<script type="text/javascript" src="http://www.recordstree.com:8081/public/js/plugins/jquery.mobilemenu.min.js"></script>
<script type="text/javascript" src="/public/js/plugins/jquery.anoslide.js"></script>
<script type="text/javascript" src="/public/js/plugins/fancybox.js"></script>
